# Generated by Django 5.1.4 on 2025-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_bloodgroup_id_alter_donor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestblood',
            name='date',
            field=models.DateField(blank=True, max_length=100),
        ),
    ]
