# Generated by Django 5.1.4 on 2025-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_donor_date_of_birth_alter_requestblood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblood',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
