# Generated by Django 5.1.4 on 2025-01-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_requestblood_is_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
