# Generated by Django 5.1.4 on 2025-01-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_donor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
