# Generated by Django 5.1.4 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_donor_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='report',
            field=models.ImageField(upload_to=''),
        ),
    ]
