# Generated by Django 5.1.4 on 2025-02-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_blog_options_remove_blog_updated_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='donor',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
