# Generated by Django 5.1.4 on 2025-02-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_blog_alter_donor_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_blocked',
        ),
    ]
