# Generated by Django 5.1.4 on 2025-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_bloodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
